In [1]:
import numpy as np

Let $x(t)=1.3t$ and $y(t)=sin(\frac{pi}{2})$ be analog signal on interval $0 \leq t\leq1$

a) Sample $x(t)$ at times $t=0, 0.25, 0.5, 0.75$ to produce sampled vector $\textbf{x}=(x(0), x(0.25), x(0.5), x(0.75)) \in \mathbb R^{4}$. Sample $y(t)$ at the same times to produce vector $\textbf{y} \in \mathbb R^{4}$

In [2]:
def x(t):
    return 1.3*t

def y(t):
    return np.sin(np.pi*0.5*t)

In [3]:
t = np.array([0, 0.25, 0.5, 0.75])

In [4]:
X = x(t)
X

array([0.   , 0.325, 0.65 , 0.975])

In [5]:
Y = y(t)
Y

array([0.        , 0.38268343, 0.70710678, 0.92387953])

In [6]:
X + Y

array([0.        , 0.70768343, 1.35710678, 1.89887953])

b) Let $q$ denote a function that takes any real number $r$ and rounds it to the nearest integer, a simple form of quantization. Use $q$ to quantize $\textbf{x}$ from part (1) component by component, to produce a quantized vector $q(\textbf{x})=(q(x_0),q(x_1),q(x_2),q(x_3))$. Do the same for $\textbf{y}$ and $\textbf{x+y}$. Show that $q(\textbf{x})+q(\textbf{y})\ne q(\textbf{x+y})$, and also that $q(2\textbf{x})\ne 2q(\textbf{x})$. Quantization is nonlinear operation!

In [7]:
def q(r):
    return np.around(r)

In [8]:
q(X)

array([0., 0., 1., 1.])

In [9]:
q(Y)

array([0., 0., 1., 1.])

In [10]:
q(X) + q(Y)

array([0., 0., 2., 2.])

In [11]:
q(X + Y)

array([0., 1., 1., 2.])

In [12]:
q(X)+q(Y) == q(X + Y)

array([ True, False, False,  True])

In [13]:
q(2*X) == 2*q(X)

array([ True, False, False,  True])